### ISSUE TITLE
apt support

### ISSUE THREAD

**Issue by lifeModder19135** [Llandy3d/sway-on-ubuntu#2]
just wanted to let you know that sway is now an apt package.  Not sure if you want to update tutorial to match.

**Comment by Llandy3d** [comment]
On ubuntu 21.04 it's more up-to-date the package, but on ubuntu 20.04 it's still on 1.4.2 unless there is a newer ppa with a more updated version that I might have missed?

Surely on 21.04 now they installation would be a lot simpler, but I also wonder if eventually we get at the same state where it becomes an "old" version and installing from source becomes again the preferred solution to get the latest features.

I was considering about making also a section for the newer ubuntu where it would be simpler with apt, but for now I also want to support Ubuntu 20.04 being LTS, thanks!

**Comment by lifeModder19135** [comment]
This is why I believe we need to invest more heavily into snaps. If devs release via snap, the framework provides a lot more assistance in the way of continuous delivery. I love the channel feature. Let me decide whether I want the stable or the newest. From what I've heard with apt, the main reason for the lag in versioning is because it needs to be thoroughly tested with the Debian system? With SNAP, it lets the user choose between the heavily tested version and the newest. That way those of us who can deal with the issues a little bit more quickly, and so for whom the risk is more worth the reward, I think the edge versions are more feasible. Thoughts. By the way, sorry for filling up your issues. I just realized yesterday that in settings GitHub let's you enable a community feature. You should check it out, if you haven't already.

**Comment by Llandy3d** [comment]
I'm not sure if snap would solve the problem. Basically both options would require someone to work on it, and the reason that there is not an up to date ubuntu 20.04 version is just because no one worked on it.
The same concept is valid for this guide aswell, if I didn't need it and made it it would probably not exist, regardless of the platform where it's published on.

I will checkout the github community feature, thanks!
